"""HTML digest rendering and SMTP delivery."""
from __future__ import annotations

import json
import os
import smtplib
from email.message import EmailMessage
from html import escape

CSS = """
body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Helvetica,Arial,sans-serif;
     background:#f6f7f9;margin:0;padding:24px;color:#1b1f24}
.wrap{max-width:720px;margin:0 auto}
h1{font-size:20px;margin:0 0 4px}
.sub{color:#667085;font-size:13px;margin:0 0 20px}
h2{font-size:14px;text-transform:uppercase;letter-spacing:.06em;color:#667085;
   margin:26px 0 10px;border-bottom:1px solid #e4e7ec;padding-bottom:6px}
.card{background:#fff;border:1px solid #e4e7ec;border-radius:10px;padding:14px 16px;
      margin-bottom:10px}
.card.target{border-left:4px solid #b45309}
.t{font-size:15px;font-weight:600;margin:0 0 2px}
.t a{color:#0b5cad;text-decoration:none}
.meta{font-size:12px;color:#667085;margin:0 0 8px}
.badge{display:inline-block;font-size:11px;font-weight:600;padding:2px 7px;
       border-radius:20px;background:#eef2f6;color:#344054;margin-right:4px}
.badge.score{background:#e7f5ec;color:#155e35}
.badge.hot{background:#fdf0e3;color:#92400e}
.kw{font-size:11px;color:#475467;margin:0}
.kw code{background:#f2f4f7;padding:1px 5px;border-radius:4px;margin-right:3px}
.badge.resume{background:#eae6fb;color:#4c3d8f}
.alt{font-size:11px;color:#98a2b3;margin:6px 0 0}
.foot{color:#98a2b3;font-size:11px;margin-top:28px;text-align:center}
.empty{background:#fff;border:1px dashed #d0d5dd;border-radius:10px;padding:22px;
       text-align:center;color:#667085;font-size:13px}
"""


def _variants(job) -> tuple[str, dict]:
    """(winning variant name, {name: score}) — empty when only one exists."""
    keys = job.keys() if hasattr(job, "keys") else job
    best = job["best_variant"] if "best_variant" in keys else None
    try:
        scores = json.loads(job["variant_scores"] or "{}") if "variant_scores" in keys else {}
    except (TypeError, ValueError):
        scores = {}
    return (best or ""), (scores if len(scores) > 1 else {})


def _card(job) -> str:
    kws = json.loads(job["matched_keywords"] or "[]")[:9]
    kw_html = "".join(f"<code>{escape(k)}</code>" for k in kws)
    bits = [b for b in (job["location"], job["department"], job["source"]) if b]
    hot = '<span class="badge hot">target</span>' if job["is_target"] else ""
    comp = f'<span class="badge">{escape(job["compensation"])}</span>' if job["compensation"] else ""

    best, scores = _variants(job)
    use = f'<span class="badge resume">use: {escape(best)}</span>' if best and scores else ""
    runners = " &middot; ".join(
        f"{escape(n)} {s:.0f}" for n, s in sorted(scores.items(), key=lambda kv: -kv[1]))
    alt = f'<p class="alt">{runners}</p>' if runners else ""

    return f"""
    <div class="card{' target' if job['is_target'] else ''}">
      <p class="t"><a href="{escape(job['url'])}">{escape(job['title'])}</a></p>
      <p class="meta">{escape(job['company'])} &middot; {escape(' &middot; '.join(bits))}</p>
      <p>{hot}<span class="badge score">{job['score']:.0f} match</span>{use}{comp}</p>
      <p class="kw">{kw_html}</p>{alt}
    </div>"""


def render_digest(jobs, title: str, subtitle: str, tiers=True) -> str:
    if not jobs:
        body = '<div class="empty">No new postings cleared your filters this week.</div>'
    elif not tiers:
        body = "".join(_card(j) for j in jobs)
    else:
        groups = {
            "Target companies": [j for j in jobs if j["is_target"]],
            "Strong matches": [j for j in jobs if not j["is_target"] and j["score"] >= 65],
            "Worth a look": [j for j in jobs if not j["is_target"] and j["score"] < 65],
        }
        body = "".join(
            f"<h2>{name} ({len(items)})</h2>" + "".join(_card(j) for j in items)
            for name, items in groups.items() if items
        )
    return f"""<!doctype html><html><head><meta charset="utf-8">
<style>{CSS}</style></head><body><div class="wrap">
<h1>{escape(title)}</h1><p class="sub">{escape(subtitle)}</p>
{body}
<p class="foot">Generated by jobhunt &middot; run <code>jobhunt list</code> for the full database</p>
</div></body></html>"""


def render_text(jobs) -> str:
    if not jobs:
        return "No new postings cleared your filters this week."
    lines = []
    for j in jobs:
        flag = "[TARGET] " if j["is_target"] else ""
        best, scores = _variants(j)
        use = f" | use: {best}" if best and scores else ""
        alt = ("\n  " + " · ".join(f"{n} {s:.0f}" for n, s in
                                   sorted(scores.items(), key=lambda kv: -kv[1]))
               if scores else "")
        lines.append(
            f"{flag}{j['title']} - {j['company']} ({j['location'] or 'n/a'})\n"
            f"  score {j['score']:.0f}{use} | {j['url']}{alt}\n"
        )
    return "\n".join(lines)


def send(config: dict, subject: str, html: str, text: str) -> None:
    cfg = config.get("email", {}) or {}
    password = os.environ.get(cfg.get("password_env", "JOBHUNT_SMTP_PASSWORD"), "")
    if not password:
        raise RuntimeError(
            f"SMTP password not set. Export ${cfg.get('password_env', 'JOBHUNT_SMTP_PASSWORD')} first."
        )

    msg = EmailMessage()
    msg["Subject"] = subject
    msg["From"] = cfg["from_addr"]
    msg["To"] = cfg["to_addr"]
    msg.set_content(text)
    msg.add_alternative(html, subtype="html")

    port = int(cfg.get("smtp_port", 587))
    host = cfg["smtp_host"]
    if port == 465:
        with smtplib.SMTP_SSL(host, port, timeout=30) as s:
            s.login(cfg["username"], password)
            s.send_message(msg)
    else:
        with smtplib.SMTP(host, port, timeout=30) as s:
            s.starttls()
            s.login(cfg["username"], password)
            s.send_message(msg)
